### PR TITLE
i18n for '_label, '_text and 'placeholder

### LINKED ISSUE #64: Resolve messages by default for certain arguments
Hi!

I think it would make sense to always lookup certain arguments in the messages.
This would be
`'_label`
`'placeholder`
`'_text` (for checkboxes)

### PR DESCRIPTION
**Pull request by mkurz**
Fixes #64 

I split the changes into different commits - so it's easier to review.

We are using this snapshot locally already and everything works fine :smile:

### CODE REVIEW

**Comment by mkurz** [comment]
Commit 1 and 4 are basically the same, so are commit 2 and 5 and commit 3 and 6

**Comment by adrianhurt** [comment]
And thanks again!!

**Comment by mkurz** [comment]
Thanks for merging :smile:
Looking forward to the updated snapshots.

**Comment by adrianhurt** [comment]
But now… what happen with arguments `_hiddenLabel`, `_help`, `_success`, `_warning` and `_error`? I'm going to find a way to localize all of them

**Comment by mkurz** [comment]
I think `_hiddenLabel` is localized now already because of how I localized `_label`.
You are right `_help`, `_success`, `_warning` and `_error` is not taken care of yet.

**Comment by adrianhurt** [comment]
Yes, I've just seen `_hiddenLabel` is not a problem. But the rest and `_label` for _FormGroups_ are. Don't worry, I'll find a solution for every case

**Comment by mkurz** [comment]
Thank you!

**Comment by mkurz** [comment]
@adrianhurt Also `_default` for `@b3.select` should be localized.

**Comment by adrianhurt** [comment]
Ok, I think now almost everything is auto-localized. I'll update the docs as soon as possible.

If you see any bug, tell me!

**Comment by mkurz** [comment]
@adrianhurt Sure I will - thanks you! I will start testing tomorrow.

**Comment by mkurz** [comment]
I had a quick look through the changes you made. So far it looks good to me. It seems the changes you made are kind of the same schema like mine - passing messages everywhere where it's needed.
I let you know of any bugs.

**Comment by adrianhurt** [comment]
Exactly, it's now automatically localized for:
* `'_label` and `'_hiddenLabel`
* `'placeholder`
* `'_help`, `'_success`, `'_warning` and `'_error`
* `'_text` for `checkbox`
* texts for `radio`, `radioOption`, `select` and `selectOption` (including `_default`)

**Pull request merged**
