### PR TITLE
Support Play 2.6.x

### PR DESCRIPTION
**Pull request by Corea**
This PR supports 2.6.0-M4. I followed migration documents from Play! Framework.

#78

### CODE REVIEW

**Comment by adrianhurt** [comment]
Wow, thanks!!! 👍 

I'll try to check it during these days and add it to master as soon as possible.

Thanks again!!

**Comment by mkurz** [comment]
You could also upgrade do sbt 0.13.15

**Comment by Corea** [comment]
@mkurz Thanks for your comments :) I just checked playframework/playframework#7209, but I guess Play! framework will use sbt 0.13.15 next milestone build or release candidate. Is it okay to do upgrade while this situation?

**Comment by mkurz** [comment]
@Corea Yes, it's completely fine to upgrade to sbt 0.13.15 here already as well.

**Comment by Corea** [comment]
@mkurz Thanks!

**Comment by Corea** [comment]
Please check this! T_T

**Comment by mkurz** [comment]
@Corea Play 2.6 RC1 was released a few hours ago. Can you please update this pull request? See: 
https://groups.google.com/d/topic/play-framework/div4xgSVsjo/discussion

**Comment by mkurz** [comment]
Play 2.6 RC2 has been released...

**Comment by adrianhurt** [comment]
I'll try to update the repo this weekend. Sorry...

**Comment by mkurz** [comment]
@adrianhurt Great, thank you!

**Comment by akkie** [comment]
Would be great to see an update :+1:

**Comment by adrianhurt** [comment]
Thanks for the PR!! I've just merge and update it. I released the last version and I've just create new SNAPSHOT versions:
- 1.1.2-P24-B3-SNAPSHOT: with Play 2.4.11, Bootstrap 3.3.7, jQuery 3.2.1
- 1.1.2-P24-B4-SNAPSHOT: with Play 2.4.11, Bootstrap 4.0.0-alpha.6, jQuery 3.2.1
- 1.1.2-P25-B3-SNAPSHOT: with Play 2.5.15, Bootstrap 3.3.7, jQuery 3.2.1
- 1.1.2-P25-B4-SNAPSHOT: with Play 2.5.15, Bootstrap 4.0.0-alpha.6, jQuery 3.2.1
- 1.1.2-P26-B3-SNAPSHOT: with Play 2.6.0-RC2, Bootstrap 3.3.7, jQuery 3.2.1, scala 2.12.2
- 1.1.2-P26-B4-SNAPSHOT: with Play 2.6.0-RC2, Bootstrap 4.0.0-alpha.6, jQuery 3.2.1, scala 2.12.2

I've also fixed issues #82 and #86.

However, I'm not going to update the documentation web for now. I've realised that in Play 2.6, the helpers now uses `MessagesProvider` instead of `Messages` as implicit, so I will try to update it as well during the next days. So, you can use this new versions to test them, but take into account this will probably change.

And again, sorry for the delay.

**Comment by adrianhurt** [comment]
I've just updated them. Now the Play 2.6 versions use the `MessagesProvider` implicit instead of `Messages`. So it uses the same pattern as the "official" helpers.

I'll try to update the docs as soon as possible.

**Comment by adrianhurt** [comment]
And the docs have been updated. Please, let me know if you see something wrong.

**Pull request merged**
