### PR TITLE
Fix links to point to Play 2.6 docs on other branch

### PR DESCRIPTION
**Pull request by mkurz**

### CODE REVIEW

**Comment by mkurz** [comment]
@adrianhurt After merging these last two pull requests - do you think you can release the final 1.2 version?
We use it since 2 weeks and it works great. I also did review the code again (diffing the `core-play25` with the `core-play26` folder and the `play25-bootstrap3` with the `play26-bootstrap3` folder). It almost didn't change anything except the message stuff.
Would be great. Thanks!

**Comment by adrianhurt** [comment]
Thanks! Ok, I'll try to release it tomorrow.

**Comment by mkurz** [comment]
Just FYI - Play 2.6.1 was released

**Comment by adrianhurt** [comment]
Sorry for the delay!! I've just released the final version.

**Comment by mkurz** [comment]
Great, thanks!

**Pull request merged**
