### PR TITLE
Upgrade to Play 2.5.6

### PR DESCRIPTION
**Pull request by mkurz**
Play 2.5.5 had a regression which needed a fix.

Could you please also release a new version? Thank you!

### CODE REVIEW

**Comment by adrianhurt** [comment]
Done! Thanks!

**Comment by mkurz** [comment]
So you release a new version?

**Comment by adrianhurt** [comment]
no, the snapshot. I will try release the final version tomorrow ;)

**Comment by mkurz** [comment]
OK I understand, thank you :smile:

**Comment by adrianhurt** [comment]
Hi! I've just released the version 1.1

**Comment by mkurz** [comment]
Thank you very much @adrianhurt!
I will upgrade tomorrow.
I really appreciate the time and effort you invest building this library! :+1:

**Pull request merged**
