### PR TITLE
b4-alpha3 form-group and label updates

### PR DESCRIPTION
**Pull request by Enalmada**
I just downloaded b4alpha3 to play with it and upon trying to use play-bootstrap it seems:
-- control-label goes away
-- form-control-label becomes col-form-label
-- form-group need to be div instead of fieldset (fieldset is for grouping multiple inputs?)

### CODE REVIEW

**Comment by adrianhurt** [comment]
Wow! I see a lot of changes in the new alpha. I'll check these as soon as possible. Meanwhile, could you discard the changes for `play25-bootstrap3/module/app/views/b3/horizontal/package.scala`, please?

Thanks!

**Comment by Enalmada** [comment]
(b3 change removed...facepalm) 
No rush, I just looked at b4 for the first time so these changes should be taken with a grain of salt as I am learning the changes.  No offence taken if you don't merge this and just use this as reference for your own alpha3 work.

**Comment by tmadge** [comment]
:+1:

**Comment by adrianhurt** [comment]
Hi! I'm sooooo sorry for doing this soooo late.

I've just released the new SNAPSHOT versions for Bootstrap 4.alpha.5:
* 1.1.1-P24-B3-SNAPSHOT
* 1.1.1-P24-B4-SNAPSHOT
* 1.1.1-P25-B3-SNAPSHOT
* 1.1.1-P25-B4-SNAPSHOT

I will update the docs as well as soon as possible.

I hope I hadn't forgot any other change of this alpha version…

BTW:
* I've decided to add `form-control-label` to the labels (but for horizontal) because they're needed for validation states.
* `help-block` _divs_ are now `form-control-feedback` _divs_ or `form-text text-muted` _smalls_.

**Comment by adrianhurt** [comment]
And don't forget the resolver

```
// Resolver is needed only for SNAPSHOT versions
resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
```

**Comment by adrianhurt** [comment]
I've just updated the docs as well

**Pull request closed without merging**
