### PR TITLE
Support Play 2.5.x

### LINKED ISSUE #53: Play 2.5 support
Hi! Play 2.5 was released yesterday.

### PR DESCRIPTION
**Pull request by stringbean**
This should be all that's required to support 2.5.x. The only changes from 2.4 are for [CSRF tokens](https://playframework.com/documentation/2.5.x/Migration25#CSRF-changes).

Fixes #53.

### CODE REVIEW

**Comment by adrianhurt** [comment]
Sorry @stringbean, thank you very much for this PR. I've been very busy these days, but I haven't forgotten it. I hope I can check this in a couple of days and merge it.

**Comment by adrianhurt** [comment]
Thanks! I've just uploaded the new versions __1.0-P5-B3-SNAPSHOT__ and __1.0-P5-B4-SNAPSHOT__. I'll update the docs as soon as possible.

**Comment by lcycon** [comment]
In case anyone finds this instead of the main docs, I think the he means `1.0-P25-B3-SNAPSHOT` and `1.0-P25-B4-SNAPSHOT`

**Comment by adrianhurt** [comment]
Exactly!

**Pull request merged**
