### PR TITLE
play27: add bootstrap3 support back

### PR DESCRIPTION
**Pull request by ahjohannessen**
Some of us are stuck with bootstrap3, but wish to upgrade to play 2.7

### CODE REVIEW

**Comment by ahjohannessen** [comment]
@adrianhurt WDYT?

**Comment by mkurz** [comment]
+1 we want to upgrade an application to Play 2.7 and we would also still need bootstrap3

**Comment by ahjohannessen** [comment]
@adrianhurt Could you please also cross publish for 2.12.8 if this gets merged?

**Comment by mkurz** [comment]
BTW Scala 2.13.0-RC2 will be release within the next couple of days, and the final release will happen soon as well :smile:

**Comment by adrianhurt** [comment]
Ok! I’ll add Bootstrap 3. Give me a couple of days. And I’ll update the docs as well. Sorry guys about not paying attention as much as I’d like

**Comment by ahjohannessen** [comment]
@adrianhurt Thanks a lot

**Comment by adrianhurt** [comment]
Sorry for not merging this PR, @ahjohannessen. I'm just updated the repo to get back the B3 versions, and I've updated the docs as well

**Comment by ahjohannessen** [comment]
@adrianhurt I don't mind if you do not merge this PR, just that b3 support is restored for Play 2.7 :)

**Comment by ahjohannessen** [comment]
@adrianhurt It would be appreciated if you could publish non-snapshot versions of 1.5-P27-B3

**Comment by adrianhurt** [comment]
Hi @ahjohannessen, please follow the conversation [here](#115)

**Pull request closed without merging**
